package:
  name: pyccapt
  version: 0.0.34

source:
  path: ../path/to/your/package/source

build:
  number: 0
  noarch: python
  script: python -m pip install . -vv

requirements:
  host:
    - python >=3.9
    - pip
  run:
    - python >=3.9
    - numpy
    - matplotlib
    - pandas
    - pyqt6
    - networkx
    - numba
    - requests
    - wget
    - h5py
    - tables
    - deepdiff
    - opencv-python
    - pyqt6-tools
    - pyqtgraph
    - nidaqmx
    - pypylon
    - pyvisa
    - pyvisa-py
    - pyserial
    - deepdiff
    - scipy
    - mcculw
    - ipywidgets
    - ipympl
    - scikit-learn
    - vispy
    - plotly
    - faker
    - jupyterlab
    - nodejs
    - adjusttext
    - pybaselines
  test:
    - pytest
    - pytest-mock
    - python >=3.9
    - ipywidgets
    - ipympl
    - scikit-learn
    - vispy
    - plotly
    - faker
    - jupyterlab
    - nodejs
    - adjusttext
    - pybaselines

test:
  imports:
    - pyccapt

about:
  home: https://github.com/mmonajem/pyccapt
  license: GPL v3
  license_file: LICENSE
  doc_url: https://pyccapt.readthedocs.io/en/latest/
  summary: A package for controlling APT experiment and calibrating the APT data

extra:
  recipe-maintainers:
    - mmonajem
