name: Python Package using Conda

on:
  push:
  pull_request:

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: pyccapt-ci
          auto-activate-base: false
          channels: conda-forge,defaults
          channel-priority: flexible
          python-version: "3.11"

      - name: Install package and test dependencies
        shell: bash -el {0}
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e ".[full,dev]"
          python -m pip install flake8

      - name: Lint with flake8
        shell: bash -el {0}
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Test calibration suite
        shell: bash -el {0}
        run: |
          pytest -q --run-calibration

      - name: Test control suite
        shell: bash -el {0}
        run: |
          pytest -q --run-control
